FROM golang:alpine AS builder
RUN apk update && apk add --no-cache gitWORKDIR $GOPATH/src/mypackage/myapp/
COPY . .
RUN go get -d -v
RUN go build -o /go/bin/za

FROM scratch
COPY --from=builder /go/bin/za /go/bin/za
ENTRYPOINT ["$ZA_ENV","/go/bin/za","$PROGRAM","$ARGS"]

