package lexer

// TokNames maps token type constants to their human-readable names.
var TokNames = [...]string{
	"ERROR", "EOL", "EOF",
	"S_LITERAL", "N_LITERAL", "IDENTIFIER",
	"OPERATOR", "S_COMMENT",
	"PLUS", "MINUS", "DIVIDE", "MULTIPLY",
	"CARET", "PLING", "PERCENT", "SEMICOLON", "ASSIGN", "ASS_COMMAND", "ASS_OUT_COMMAND", "LBRACE", "RBRACE", "LCBRACE", "RCBRACE",
	"PLUSEQ", "MINUSEQ", "MULEQ", "DIVEQ", "MODEQ", "LPAREN", "RPAREN",
	"SYM_EQ", "SYM_LT", "SYM_LE", "SYM_GT", "SYM_GE", "SYM_NE",
	"SYM_LAND", "SYM_LOR", "SYM_BAND", "SYM_BOR", "SYM_BSLASH", "SYM_DOT", "SYM_PP", "SYM_MM", "SYM_POW", "SYM_RANGE",
	"SYM_LSHIFT", "SYM_RSHIFT", "SYM_COLON", "SYM_DCOLON", "COMMA", "TILDE", "ITILDE", "FTILDE", "SQR", "SQRT",
	"O_QUERY", "O_TRY", "O_FILTER", "O_MAP", "O_INFILE", "O_OUTFILE", "O_REF", "O_MUT", "O_LC", "O_UC", "O_ST", "O_LT", "O_RT",
	"O_PB", "O_PA", "O_PN", "O_PE", "O_PP",
	"START_STATEMENTS", "VAR", "SETGLOB",
	"INIT", "IN", "PAUSE", "HELP", "NOP", "HIST", "DEBUG", "REQUIRE", "EXIT", "VERSION",
	"QUIET", "LOUD", "UNSET", "INPUT", "PROMPT", "LOG", "PRINT", "PRINTLN",
	"LOGGING", "CLS", "AT", "DEFINE", "SHOWDEF", "ENDDEF", "RETURN", "ASYNC",
	"LIB", "MODULE", "NAMESPACE", "USE", "USES", "WHILE", "ENDWHILE", "FOR", "FOREACH",
	"ENDFOR", "CONTINUE", "BREAK", "IF", "ELSE", "ENDIF", "CASE",
	"IS", "CONTAINS", "HAS", "OR", "ENDCASE", "WITH", "ENDWITH", "STRUCT", "ENDSTRUCT", "SHOWSTRUCT",
	"PANE", "DOC", "TEST", "ENDTEST", "ASSERT", "ON", "TO", "STEP", "AS", "DO", "MACRO", "ENUM",
	"TRY", "CATCH", "THEN", "THROWS", "THROW", "ENDTRY",
	"BLOCK", "ABLOCK", "RBLOCK",
	"T_NUMBER", "T_NIL", "T_BOOL", "T_INT", "T_UINT", "T_FLOAT", "T_BIGI",
	"T_BIGF", "T_STRING", "T_MAP", "T_ARRAY", "T_ANY", "T_POINTER",
}
