#!/bin/bash

seconds=${1:-20}

go tool pprof -alloc_objects -http localhost:8080 http://localhost:8008/debug/pprof/heap?seconds=${seconds}
# go tool pprof -alloc_space -http localhost:6000 http://localhost:6060/debug/pprof/heap?seconds=${seconds}

