# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-Za-Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
        
    - name: Install-Upx
      run: sudo apt install -y upx

    - name: Find-Version
      id: find-version
      run: echo "za_version=$(< VERSION)" >> "$GITHUB_OUTPUT"

    - name: Pre-Build
      run: go build za

    - name: Build-Alpine
      run: ./za build alpine upx strip

    - name: Build-Linux
      run: ./za build strip

    # copy binary artifact to final location:
    
    - uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "za,za.alpine"
        tag: ${{ steps.find-version.outputs.za_version }}
        draft: true
        
        





