# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Install-Upx
      run: apt install -y upx
     
    - name: Find-Version
      run: za_version=$(< VERSION)

    - name: Pre-Build
      run: go build za

    - name: Build-Alpine
      run: ./za build alpine

    - name: Build-Linux
      run: ./za build
      
# copy binary artifact to final location:






